#!/usr/bin/env python2

from twisted.web.xmlrpc import Proxy
from twisted.internet import reactor

if __name__ == "__main__":
    p = Proxy('http://localhost:5000')
    d = p.callRemote('hello', 'you')
    def print_(x): print x
    d.addCallbacks(print_, print_)

    reactor.run()
