#!/usr/bin/env python2
import pickle
import sys

from twisted.web.xmlrpc import Proxy
from twisted.internet import reactor
from twisted.python import log
log.startLogging(sys.stdout)

def _print(x):
    print x
    return x

class RPCClient(object):
    def __init__(self, addr_str='http://localhost:5000'):
        self.proxy = Proxy(addr_str)

    def start_loop(self):
        reactor.run()

    def ping(self, address_str):
        log.msg('ping({0})'.format(address_str))
        return self._call('ping', address_str)

    def find_node(self, address_str, node_id):
        log.msg('find_node({0}, {1})'.format(address_str, node_id))
        s_node_id = self._serialize(node_id)
        return self._call('find_node', address_str, s_node_id)

    def get_peers(self, address_str, node_id):
        log.msg('get_peers({0}, {1})'.format(address_str, node_id))
        s_node_id = self._serialize(node_id)
        return self._call('get_peers', address_str, s_node_id)

    def get(self, target_id):
        log.msg('get({0})'.format(target_id))
        s_target_id = self._serialize(target_id)
        return self._call('get', s_target_id)

    def grab_nodes(self):
        return self._call('grab_nodes')

    def _deserialize(self, serial_val):
        return pickle.loads(serial_val)

    def _serialize(self, val):
        return pickle.dumps(val)

    def _call(self, funcname, *args, **kwargs):
        # TODO refactor the above log.msg calls
        # into this function here
        d = self.proxy.callRemote(funcname, *args, **kwargs)
        d.addBoth(self._deserialize)
        d.addBoth(_print)
        return d


if __name__ == "__main__":
    address_str = 'weezy.us:1337'
    example = 0x982AE8129CEDABED2E8DD4735E3E00A0CE2E7509
    rpc_client = RPCClient()
    rpc_client.ping(address_str)
    rpc_client.find_node(address_str, example)
    rpc_client.get_peers(address_str, example)
    rpc_client.get(example)

    # // TODO clean shutdown
    rpc_client.start_loop()
