#!/usr/bin/env python2
import pickle

from twisted.web.xmlrpc import Proxy
from twisted.internet import reactor

def _print(x, *a, **k): print x, a, k

if __name__ == "__main__":
    p = Proxy('http://localhost:5000')
    d = p.callRemote('ping', 'weezy.us:1337')
    d.addCallbacks(_print, _print)
    d.addCallbacks(pickle.loads, pickle.loads)
    d.addCallbacks(_print, _print)

    reactor.run()
